Revert "Import org.junit.Assert instead of junit.framework.Assert."
This reverts commit 60a5a850f0268ca617005e8b7f480049f0c8c9bc.

It broke Android builds:
app/webrtc/java/testcommon/src/org/webrtc/PeerConnectionTest.java:46: error: package org.junit does not exist
import static org.junit.Assert.*;
                       ^
TBR=glaznev@webrtc.org,pthatcher@webrtc.org
BUG=none

Review URL: https://webrtc-codereview.appspot.com/52039004

Cr-Commit-Position: refs/heads/master@{#9357}