Fix no_exit_time_destructors in pc.
This CL fixes the following error:
pc/peerconnection.cc:396:7:
error: declaration requires an exit-time destructor
[-Werror,-Wexit-time-destructors]
      proto_media_counter_map = {

It moves the protocol to media map into PeerConnection's attributes, the
map is initialized during PeerConnection::Initialize.
This removes the need of using 'static' and it should not cause too much
overhead since the map is initialized only once for each PeerConnection.

Bug: webrtc:9693
Change-Id: Icd71a70204ccc6fb032af52c64afa59e9aa7af74
Reviewed-on: https://webrtc-review.googlesource.com/98780
Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
Reviewed-by: Steve Anton <steveanton@webrtc.org>
Reviewed-by: Karl Wiberg <kwiberg@webrtc.org>
Cr-Commit-Position: refs/heads/master@{#24674}