Revert of Remove typedefs.h from webrtc/ root (part 1) (patchset #3 id:40001 of https://codereview.webrtc.org/3007253002/ )
Reason for revert:
Breaks the Chromium WebRTC FYI bots:
https://build.chromium.org/p/chromium.webrtc.fyi/builders/ios-simulator/builds/2834
https://build.chromium.org/p/chromium.webrtc.fyi/builders/Win%20Builder/builds/11775

Example:
FAILED: obj/third_party/libjingle_xmpp/libjingle_xmpp_unittests/xmpplogintask_unittest.obj
ninja -t msvc -e environment.x86 -- E:\b\c\goma_client/gomacc.exe "e:\b\c\win_toolchain\vs_files\f53e4598951162bad6330f7a167486c7ae5db1e5\vc\bin\amd64_x86/cl.exe" /nologo /showIncludes  @obj/third_party/libjingle_xmpp/libjingle_xmpp_unittests/xmpplogintask_unittest.obj.rsp /c ../../third_party/libjingle_xmpp/xmpp/xmpplogintask_unittest.cc /Foobj/third_party/libjingle_xmpp/libjingle_xmpp_unittests/xmpplogintask_unittest.obj /Fd"obj/third_party/libjingle_xmpp/libjingle_xmpp_unittests_cc.pdb"
../../third_party/libjingle_xmpp/xmpp/xmpplogintask_unittest.cc(95): error C3861: 'FALLTHROUGH': identifier not found

Original issue's description:
> Remove typedefs.h from webrtc/ root (part 1)
>
> Split out webrtc-specific #defines from typedefs.h, into rtc_base/annotations.h and rtc_base/arch.h.
> Also removes the curiously named WEBRTC_CPU_DETECTION #define.
>
> BUG=webrtc:6854
>
> Review-Url: https://codereview.webrtc.org/3007253002
> Cr-Commit-Position: refs/heads/master@{#19752}
> Committed: https://chromium.googlesource.com/external/webrtc/+/88f4ee7e66f804847b7e4e0681cd5ca5a2261084

TBR=kwiberg@webrtc.org,solenberg@webrtc.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=webrtc:6854

Review-Url: https://codereview.webrtc.org/3013543002
Cr-Commit-Position: refs/heads/master@{#19754}