Revert "Drop tools/gyp from dependencies."
This reverts commit a5c645599977723a67bd010dafd201eedb4179ba.

Reason for revert: We have this error during gclient runhooks on some
windows bots:
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-334100-1.tgz .......... Done.
Traceback (most recent call last):
  File "src/tools/clang/scripts/update.py", line 927, in <module>
    sys.exit(main())
  File "src/tools/clang/scripts/update.py", line 923, in main
    return UpdateClang(args)
  File "src/tools/clang/scripts/update.py", line 470, in UpdateClang
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "src/tools/clang/scripts/update.py", line 396, in CopyDiaDllTo
    dia_path = os.path.join(GetVSVersion().Path(), 'DIA SDK', 'bin', 'amd64')
  File "src/tools/clang/scripts/update.py", line 388, in GetVSVersion
    import gyp.MSVSVersion
ImportError: No module named gyp.MSVSVersion

Looks like if toolchain is not downloaded before then it failed to
download it from scratch.

Original change's description:
> Drop tools/gyp from dependencies.
> 
> Bug: webrtc:6323
> Change-Id: I894f0ea95fb6707242a061947b4f4602b48910e6
> Reviewed-on: https://webrtc-review.googlesource.com/6763
> Reviewed-by: Patrik Höglund <phoglund@webrtc.org>
> Commit-Queue: Niels Moller <nisse@webrtc.org>
> Cr-Commit-Position: refs/heads/master@{#23613}

TBR=phoglund@webrtc.org,nisse@webrtc.org

Change-Id: I38ff915cccfdcc80af9e2f82130bccd33bf7ea86
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: webrtc:6323
Reviewed-on: https://webrtc-review.googlesource.com/83744
Reviewed-by: Artem Titov <titovartem@webrtc.org>
Commit-Queue: Artem Titov <titovartem@webrtc.org>
Cr-Commit-Position: refs/heads/master@{#23617}